name: compil
on: [push, pull_request]

jobs:
  compil_job:
    runs-on: ubuntu-latest
    name: compil
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t compil .github/compil
    - run: docker run -v $PWD:/.github/compil/ compil 
